CREATE TABLE smokers (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(15) NULL DEFAULT NULL,
  `timezone` VARCHAR(15) NULL DEFAULT NULL,
  `progress` INTEGER NULL DEFAULT NULL,
  `reminder` VARCHAR(15) NULL DEFAULT NULL, 
  PRIMARY KEY (`id`)
)

CREATE TABLE friends (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  'id_smokers' INTEGER NOT NULL
  PRIMARY KEY (`id`)
)

ALTER TABLE `friends` ADD FOREIGN KEY (id_smokers) REFERENCES `smokers` (`id`);